name: build

on:
  schedule:
      # * is a special character in YAML so you have to quote this string
      - cron:  '0 0 1 * *'

  # allows you to run this workflow manually from actions tab
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Check for javascript library vulnerabilities
        uses: lirantal/is-website-vulnerable@master
        with:
          scan-url: "https://jchinnam.github.io"

  availability:
    runs-on: ubuntu-latest
    steps:
      - name: Pull sources
        uses: actions/checkout@v2
      - name: Ping
        id: query
        uses: CamiloGarciaLaRotta/watermelon-http-client@v1
        with:
          url: 'https://jchinnam.github.io'
      - name: Print response status
        run: echo ${{ steps.query.outputs.status }}
        shell: bash
      - name: Print response headers
        run: echo ${{ steps.query.outputs.headers }}
        shell: bash
      - name: Print response payload
        run: echo ${{ steps.query.outputs.response }}
        shell: bash

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Pull sources
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Run npm ci
        run: npm ci
      - name: Lint
        run: npm run lint
